// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMtHHXYHcZwrI-RSoghxO_vZvOId9Rs6c',
    appId: '1:841068724515:web:2efd44647977a26b7a0c96',
    messagingSenderId: '841068724515',
    projectId: 'ourarchive-7d7ba',
    authDomain: 'ourarchive-7d7ba.firebaseapp.com',
    storageBucket: 'ourarchive-7d7ba.firebasestorage.app',
    measurementId: 'G-YTCJDMLFPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdiUcFUqAJTvRNYEJjkt2GAa87yFeC5eg',
    appId: '1:841068724515:android:5b13eca159cf09837a0c96',
    messagingSenderId: '841068724515',
    projectId: 'ourarchive-7d7ba',
    storageBucket: 'ourarchive-7d7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQwHB_YGz51Qk_gaikBCdrCMuHCwCehA',
    appId: '1:841068724515:ios:0d0b03f85d8612d57a0c96',
    messagingSenderId: '841068724515',
    projectId: 'ourarchive-7d7ba',
    storageBucket: 'ourarchive-7d7ba.firebasestorage.app',
    iosBundleId: 'com.gustafeden.ourArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClQwHB_YGz51Qk_gaikBCdrCMuHCwCehA',
    appId: '1:841068724515:ios:a14c092e4c84b4427a0c96',
    messagingSenderId: '841068724515',
    projectId: 'ourarchive-7d7ba',
    storageBucket: 'ourarchive-7d7ba.firebasestorage.app',
    iosBundleId: 'com.example.ourArchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMtHHXYHcZwrI-RSoghxO_vZvOId9Rs6c',
    appId: '1:841068724515:web:2e35a589b5d5a8887a0c96',
    messagingSenderId: '841068724515',
    projectId: 'ourarchive-7d7ba',
    authDomain: 'ourarchive-7d7ba.firebaseapp.com',
    storageBucket: 'ourarchive-7d7ba.firebasestorage.app',
    measurementId: 'G-JJ2DDT8X2N',
  );
}
