import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAuth.instance.signInAnonymously(); // no login UI
  runApp(const OurArchiveApp());
}

class OurArchiveApp extends StatelessWidget {
  const OurArchiveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'OurArchive',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF3C5548)),
        useMaterial3: true,
      ),
      home: const ArchiveHomePage(),
    );
  }
}

class ArchiveHomePage extends StatelessWidget {
  const ArchiveHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final items = FirebaseFirestore.instance.collection('archive_items');
    return Scaffold(
      appBar: AppBar(title: const Text('OurArchive')),
      body: StreamBuilder<QuerySnapshot>(
        stream: items.snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
          final docs = snapshot.data!.docs;
          return ListView(
            children: docs.map((doc) {
              final data = doc.data()! as Map<String, dynamic>;
              return ListTile(
                title: Text(data['title'] ?? 'Untitled'),
                subtitle: Text(data['type'] ?? ''),
              );
            }).toList(),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await items.add({
            'title': 'Example Item',
            'type': 'Book',
            'timestamp': DateTime.now(),
            'user': FirebaseAuth.instance.currentUser?.uid,
          });
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
