import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'logger_service.dart';

class LogExportService {
  final LoggerService _logger;

  LogExportService(this._logger);

  /// Share logs using iOS/Android share sheet
  Future<bool> shareLogs() async {
    try {
      final logFile = _logger.logFile;
      if (logFile == null || !await logFile.exists()) {
        return false;
      }

      final result = await Share.shareXFiles(
        [XFile(logFile.path)],
        subject: 'OurArchive Debug Logs',
        text: 'Debug logs from OurArchive app',
      );

      return result.status == ShareResultStatus.success;
    } catch (e) {
      debugPrint('Failed to share logs: $e');
      return false;
    }
  }

  /// Email logs as attachment
  Future<bool> emailLogs({String? recipientEmail}) async {
    try {
      final logFile = _logger.logFile;
      if (logFile == null || !await logFile.exists()) {
        return false;
      }

      // Get app version info
      final packageInfo = await PackageInfo.fromPlatform();
      final appVersion = packageInfo.version;
      final buildNumber = packageInfo.buildNumber;

      // Get device info
      final platform = Platform.operatingSystem;
      final version = Platform.operatingSystemVersion;

      // Prepare email content
      final recipient = recipientEmail ?? '';
      final subject = Uri.encodeComponent('OurArchive Debug Logs - v$appVersion+$buildNumber');
      final body = Uri.encodeComponent('''
App Version: $appVersion ($buildNumber)
Platform: $platform
OS Version: $version

Please find the debug logs attached.

---
This email was generated by OurArchive app.
''');

      // Create mailto URL
      final mailtoUrl = Uri.parse('mailto:$recipient?subject=$subject&body=$body');

      // Try to launch email client
      if (await canLaunchUrl(mailtoUrl)) {
        await launchUrl(mailtoUrl);

        // After opening email client, share the log file
        // (user will need to manually attach it since mailto doesn't support attachments)
        await shareLogs();

        return true;
      } else {
        // Fallback to share if email client not available
        return await shareLogs();
      }
    } catch (e) {
      debugPrint('Failed to email logs: $e');
      return false;
    }
  }

  /// Get a formatted summary of app and device info
  Future<String> getDeviceInfo() async {
    try {
      final packageInfo = await PackageInfo.fromPlatform();

      return '''
App Name: ${packageInfo.appName}
Version: ${packageInfo.version}
Build: ${packageInfo.buildNumber}
Package: ${packageInfo.packageName}

Platform: ${Platform.operatingSystem}
OS Version: ${Platform.operatingSystemVersion}
Locale: ${Platform.localeName}
''';
    } catch (e) {
      return 'Unable to retrieve device info: $e';
    }
  }

  /// Show a dialog with options to send logs
  Future<void> showSendLogsDialog(BuildContext context) async {
    final logFile = _logger.logFile;
    final hasLogs = logFile != null && await logFile.exists();

    if (!hasLogs) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('No logs available')),
        );
      }
      return;
    }

    final fileSize = await logFile.length();
    final fileSizeKB = (fileSize / 1024).toStringAsFixed(1);

    if (!context.mounted) return;

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Send Debug Logs'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('This will share your app debug logs to help diagnose issues.'),
            const SizedBox(height: 16),
            Text(
              'Log file size: $fileSizeKB KB',
              style: Theme.of(context).textTheme.bodySmall,
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () async {
              Navigator.pop(context);
              final success = await emailLogs();
              if (context.mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      success
                          ? 'Opening email client...'
                          : 'Failed to send logs. Please try Share instead.',
                    ),
                  ),
                );
              }
            },
            child: const Text('Email'),
          ),
          FilledButton(
            onPressed: () async {
              Navigator.pop(context);
              final success = await shareLogs();
              if (context.mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      success
                          ? 'Logs shared successfully'
                          : 'Failed to share logs',
                    ),
                  ),
                );
              }
            },
            child: const Text('Share'),
          ),
        ],
      ),
    );
  }
}
